feat(dart_frog_cli): added progress indicator for hot reload
VeryGoodOpenSource/dart_frog pull request #1146
Opened 2023-11-14 03:07 UTC by dhruvpatidar359

## Status

**READY**

## Description

Added progress indicator during hot reload

## Type of Change

- [x ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-11-23 14:41 UTC, renancaraujo requested changes
Apart from the points added to this review, o think we should not use progress on the daemon, it makes the event a little hard to parse.

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +    if (logProgress == null) {
```suggestion
    if (!showProgress) {
```

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +  Future<void> _reload([bool verbose = false, bool progress = true]) async {
```suggestion
  Future<void> _reload([bool verbose = false, bool showProgress = true]) async {
```

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +  Future<void> _reload([bool verbose = false, bool progress = true]) async {
At this point we should start using named parameters

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +    final logInfoOrDetail = verbose ? logger.info : logger.detail;
I don't understand the refactor on the name from `log` to `logInfoOrDetail`.

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +    if (logProgress == null) {
The nullability of `logProgress` is not the condition here, `showProgress` is.

2023-11-23 14:41 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
> +    return _reload(infoOrDetail, progress);
Is this breaking API addressed somewhere? Verbose was true before.

2023-11-26 15:25 UTC, dhruvpatidar359 commented
> Apart from the points added to this review, o think we should not use progress on the daemon, it makes the event a little hard to parse.



> Apart from the points added to this review, o think we should not use progress on the daemon, it makes the event a little hard to parse.

Alright that means for showing the time, we can use the timer sort of thing . But we can't use the progress ,i can't show the progress sort of thing . Should i implement kind of custom logging here ?

2023-11-27 15:53 UTC, renancaraujo commented
As we are working on https://github.com/VeryGoodOpenSource/dart_frog/issues/1016, the code to be changed here tends to move around a little in the next few days, so I think it is better to wait for that before tackling this. 

Thanks for opening the issue and your time dedicated to this.

2023-11-27 15:53 UTC, closed without merging