docs(resources): add awesome dart frog
VeryGoodOpenSource/dart_frog pull request #545
Opened 2023-02-17 22:56 UTC by scarletteliza

## Status

**READY**

## Description

Add link to Awesome Dart Frog repo

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

2023-02-17 23:59 UTC, renancaraujo approved these changes

2023-02-18 00:13 UTC, wolfenrain approved these changes

2023-02-18 17:36 UTC, felangel commented on docs/docs/basics/resources.md
> +- [Awesome Dart Frog repo]: Highlights awesome Dart Frog resources — articles, videos, open source projects, and more!
Looks like we aren’t referencing the awesome_df link here

2023-02-18 17:36 UTC, felangel requested changes
See comment

2023-02-21 17:27 UTC, felangel commented on docs/docs/basics/resources.md
> +[awesome_df]: https://github.com/VeryGoodOpenSource/awesome-dart-frog
```suggestion
[awesome_dart_frog_link]: https://github.com/VeryGoodOpenSource/awesome-dart-frog
```

2023-02-21 17:27 UTC, felangel commented on docs/docs/basics/resources.md
> +- [Awesome Dart Frog repo][awesome_df]: Highlights awesome Dart Frog resources — articles, videos, open source projects, and more!
```suggestion
- [Awesome Dart Frog repo][awesome_dart_frog_link]: Highlights awesome Dart Frog resources — articles, videos, open source projects, and more!
```

2023-02-21 17:28 UTC, felangel approved these changes

2023-02-21 17:29 UTC, merged