feat(dart_frog): Expose shelf's additional Response constructors
VeryGoodOpenSource/dart_frog pull request #606
Opened 2023-04-13 13:08 UTC by Spiritcow

closes https://github.com/VeryGoodOpenSource/dart_frog/issues/594

Do not be covered with tests, because it's covered in the shelf itself.

## Status

**READY**

## Description

Expose shelf's additional Response constructors:

- [badRequest](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.badRequest.html)
- [forbidden](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.forbidden.html)
- [found](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.found.html)
- [internalServerError](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.internalServerError.html)
- [movedPermanently](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.movedPermanently.html)
- [notFound](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.notFound.html)
- [notModified](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.notModified.html)
- [ok](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.ok.html)
- [seeOther](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.seeOther.html)
- [unauthorized](https://pub.dev/documentation/shelf/latest/shelf/Response/Response.unauthorized.html)

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-04-14 10:01 UTC, easazade approved these changes

2023-04-25 18:58 UTC, alestiago requested changes
Requesting changes until the conversation from https://github.com/VeryGoodOpenSource/dart_frog/issues/594 is resolved.

2023-05-24 16:56 UTC, alestiago commented
@Spiritcow would you like to make the amendments to the PR to fit with https://github.com/VeryGoodOpenSource/dart_frog/issues/594#issuecomment-1551710795?

2023-07-13 07:51 UTC, alestiago commented
I'm closing this issue due to inactivity of the original author 💙 . Feel free to re-open or create a new Pull Request to address the isssue.

2023-07-13 07:51 UTC, closed without merging