feat(dart_frog_cli): support lowercase r to reload
VeryGoodOpenSource/dart_frog pull request #900
Opened 2023-08-07 15:14 UTC by Yczar

## Status

**READY*

## Description

 This change adds support lowercase r to reload.
 fixes #893 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-08-07 16:23 UTC, renancaraujo approved these changes

2023-08-07 16:24 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/commands/dev/dev.dart
> +                event.first == 'r'.codeUnitAt(0))) {
Actually we will need tests for this

2023-08-07 16:24 UTC, renancaraujo requested changes
Need tests

2023-08-07 16:39 UTC, renancaraujo commented on packages/dart_frog_cli/lib/src/commands/dev/dev.dart
> +                event.first == 'r'.codeUnitAt(0))) {
@Yczar would you need assitance to add tests for this?

2023-08-08 13:04 UTC, Yczar commented
@renancaraujo done!

2023-08-14 12:56 UTC, Yczar commented
Hey @renancaraujo were you able to check this out?

2023-08-14 12:59 UTC, renancaraujo approved these changes

2023-08-23 13:03 UTC, erickzanardo approved these changes

2023-08-23 13:15 UTC, merged